#!/bin/bash

NLPDIR=/home/yoshimura/src/nlp
NLPBIN=`ls ${NLPDIR}/target/nlp-*-jar-with-dependencies.jar`
CONF=${NLPDIR}/conf.json

java -cp `hadoop classpath`:${NLPBIN} \
	 ac.keio.sslab.nlp.CliMain ${@} NLPCONF=${CONF}